import type { AchievementDef } from '../types'

export const ACHIEVEMENTS: AchievementDef[] = [
  {
    key: 'first_rep',
    name: 'First Rep',
    description: 'Log your very first rep',
    icon: 'zap',
    rule: (s) => s.totalReps >= 1,
    progress: (s) => ({ current: Math.min(s.totalReps, 1), target: 1 }),
  },
  {
    key: 'century',
    name: 'Century Club',
    description: 'Reach 100 total reps',
    icon: 'award',
    rule: (s) => s.totalReps >= 100,
    progress: (s) => ({ current: Math.min(s.totalReps, 100), target: 100 }),
  },
  {
    key: 'thousand',
    name: 'Thousandaire',
    description: 'Reach 1,000 total reps',
    icon: 'crown',
    rule: (s) => s.totalReps >= 1000,
    progress: (s) => ({ current: Math.min(s.totalReps, 1000), target: 1000 }),
  },
  {
    key: 'streak_3',
    name: '3-Day Streak',
    description: 'Work out 3 days in a row',
    icon: 'flame',
    rule: (s) => s.currentStreak >= 3,
    progress: (s) => ({ current: Math.min(s.currentStreak, 3), target: 3 }),
  },
  {
    key: 'streak_7',
    name: 'Weekly Warrior',
    description: 'Work out 7 days in a row',
    icon: 'shield',
    rule: (s) => s.currentStreak >= 7,
    progress: (s) => ({ current: Math.min(s.currentStreak, 7), target: 7 }),
  },
  {
    key: 'streak_30',
    name: 'Monthly Monster',
    description: 'Work out 30 days in a row',
    icon: 'trophy',
    rule: (s) => s.currentStreak >= 30,
    progress: (s) => ({ current: Math.min(s.currentStreak, 30), target: 30 }),
  },
  {
    key: 'five_exercises',
    name: 'Well Rounded',
    description: 'Use 5 different exercises',
    icon: 'target',
    rule: (s) => s.uniqueExercises >= 5,
    progress: (s) => ({ current: Math.min(s.uniqueExercises, 5), target: 5 }),
  },
  {
    key: 'daily_goal',
    name: 'Goal Crusher',
    description: 'Hit your daily rep goal',
    icon: 'check-circle',
    rule: (s) => s.todayReps >= s.dailyGoal,
    progress: (s) => ({ current: Math.min(s.todayReps, s.dailyGoal), target: s.dailyGoal }),
  },
  {
    key: 'early_bird',
    name: 'Early Bird',
    description: 'Log reps before 7am',
    icon: 'sunrise',
    rule: (s) => s.loggedBefore7am,
    progress: (s) => ({ current: s.loggedBefore7am ? 1 : 0, target: 1 }),
  },
  {
    key: 'night_owl',
    name: 'Night Owl',
    description: 'Log reps after 10pm',
    icon: 'moon',
    rule: (s) => s.loggedAfter10pm,
    progress: (s) => ({ current: s.loggedAfter10pm ? 1 : 0, target: 1 }),
  },
]
