import {
  Activity,
  ArrowDown,
  ArrowDownToLine,
  ArrowUpFromLine,
  Award,
  Bolt,
  CheckCircle,
  ChevronsUp,
  CircleDot,
  Crown,
  Diamond,
  Dumbbell,
  Flame,
  FlipVertical2,
  Footprints,
  Heart,
  Hexagon,
  Minimize2,
  Moon,
  Mountain,
  MoveHorizontal,
  Octagon,
  Shield,
  Star,
  Sunrise,
  Target,
  Timer,
  TrendingUp,
  Triangle,
  Trophy,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/**
 * Every icon reachable by name (exercise seeds, the add-exercise picker, and
 * achievement badges). Explicit imports keep lucide tree-shakeable — importing
 * the full `icons` record used to ship the entire library (~700 kB min).
 * Unknown names fall back to `activity` in DynamicIcon.
 */
export const ICON_MAP: Record<string, LucideIcon> = {
  activity: Activity,
  'arrow-down': ArrowDown,
  'arrow-down-to-line': ArrowDownToLine,
  'arrow-up-from-line': ArrowUpFromLine,
  award: Award,
  bolt: Bolt,
  'check-circle': CheckCircle,
  'chevrons-up': ChevronsUp,
  'circle-dot': CircleDot,
  crown: Crown,
  diamond: Diamond,
  dumbbell: Dumbbell,
  flame: Flame,
  'flip-vertical-2': FlipVertical2,
  footprints: Footprints,
  heart: Heart,
  hexagon: Hexagon,
  'minimize-2': Minimize2,
  moon: Moon,
  mountain: Mountain,
  'move-horizontal': MoveHorizontal,
  octagon: Octagon,
  shield: Shield,
  star: Star,
  sunrise: Sunrise,
  target: Target,
  timer: Timer,
  'trending-up': TrendingUp,
  triangle: Triangle,
  trophy: Trophy,
  zap: Zap,
}
